services:
  webserver:
    build:
      context: c-web
      dockerfile: Dockerfile
    container_name: phpcensosuas
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./c-web/www:/var/www/html
    networks:
      - redeappcensosuas
  database:
    hostname: dbcensosuas
    build:
      context: c-db
      dockerfile: Dockerfile
    container_name: dbcensosuas
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - '5432:5432'
    volumes:
      - ./c-db/data:${POSTGRES_DATA}
      - ./c-db/dados.sql:/docker-entrypoint-initdb.d/dados.sql
    networks:
      - redeappcensosuas
networks:
    redeappcensosuas:
        driver: bridge