services:
  webserver:
    build:
      context: c-web
      dockerfile: Dockerfile
    container_name: webserverphp
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./c-web/www:/var/www/html
    networks:
      - redeappcensosuas

  database:    
    build:
      context: c-db
      dockerfile: Dockerfile
    container_name: databasepostgres
    restart: always
    environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    networks:
      - redeappcensosuas

networks:
    redeappcensosuas:
        driver: bridge