services:
  phpcensosuas:
    hostname: phpcensosuas
    build:
      context: ./
      dockerfile: Dockerfile-php
    container_name: phpcensosuas
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./www:/var/www/html
    networks:
      - redecensosuas
  pgcensosuas:
    hostname: pgcensosuas
    build:
      context: ./
      dockerfile: Dockerfile-pg
    container_name: dbcensosuas
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - '5432:5432'
    volumes:
      - ./data:${POSTGRES_DATA}
      - ./dados.sql:/docker-entrypoint-initdb.d/dados.sql
    networks:
      - redecensosuas
networks:
    redecensosuas:
        driver: bridge